using Dapper;
using DataAccessLibrary.Models;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Logging;
using System.Data;

namespace DataAccessLibrary.Repositories;

/// <summary>
/// High-performance Dapper-based Campaign Repository
/// </summary>
public class CampaignRepository : ICampaignRepository
{
    private readonly string _connectionString;
    private readonly IGlobalLogger _logger;

    public CampaignRepository(IConfiguration configuration, IGlobalLogger logger)
    {
        _connectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new ArgumentNullException("ConnectionString not found");
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    // ========================================
    // CAMPAIGN OPERATIONS
    // ========================================

    public async Task<Campaign> CreateCampaignAsync(Campaign campaign, CancellationToken cancellationToken = default)
    {
        _logger.LogMethodEntry(nameof(CreateCampaignAsync));

        const string sql = @"
INSERT INTO Campaigns (
    Id, Name, Description, CampaignType, ReviewType,
    ConnectionScope, ObjectClassFilter, DepartmentFilter, RiskLevelFilter, PolicyViolationFilter, CustomScopeFilter,
    IncludeNestedMemberships, MaxNestedDepth,
    StartDate, EndDate, DueDate, ReviewPeriodDays,
    Status, CompletionPercentage, TotalAssignments, CompletedAssignments,
    AutoGenerated, SourcePolicyExecutionId, SourcePolicyId, ParentCampaignId, IsRecurring, RecurrencePattern,
    AssignmentStrategy, CaseAssigneeId, CaseAssigneeName,
    NotificationSettings, EscalationSettings, EnableNotifications, ReminderDaysBefore,
    AssignmentEmailTemplateId, ReminderEmailTemplateId,
    OwnerId, OwnerName, NotificationCcEmails, EnableTeamsNotifications,
    CreatedBy, CreatedAt, ComplianceFramework,
    OnDenialAction, AutoRemediateOnDenial, OnIncompleteAction, OnApprovalAction, EscalationReviewerId, ExtensionDays,
    CompletionActionsProcessed, WorkflowId,
    ScopeLevel,
    RecurrenceType, RecurrenceInterval, RecurrenceStartDate, AutoLaunch,
    CampaignDurationDays, NextScheduledRun, IsRecurrencePaused, IsRecurrenceClone
) VALUES (
    @Id, @Name, @Description, @CampaignType, @ReviewType,
    @ConnectionScope, @ObjectClassFilter, @DepartmentFilter, @RiskLevelFilter, @PolicyViolationFilter, @CustomScopeFilter,
    @IncludeNestedMemberships, @MaxNestedDepth,
    @StartDate, @EndDate, @DueDate, @ReviewPeriodDays,
    @Status, @CompletionPercentage, @TotalAssignments, @CompletedAssignments,
    @AutoGenerated, @SourcePolicyExecutionId, @SourcePolicyId, @ParentCampaignId, @IsRecurring, @RecurrencePattern,
    @AssignmentStrategy, @CaseAssigneeId, @CaseAssigneeName,
    @NotificationSettings, @EscalationSettings, @EnableNotifications, @ReminderDaysBefore,
    @AssignmentEmailTemplateId, @ReminderEmailTemplateId,
    @OwnerId, @OwnerName, @NotificationCcEmails, @EnableTeamsNotifications,
    @CreatedBy, @CreatedAt, @ComplianceFramework,
    @OnDenialAction, @AutoRemediateOnDenial, @OnIncompleteAction, @OnApprovalAction, @EscalationReviewerId, @ExtensionDays,
    @CompletionActionsProcessed, @WorkflowId,
    @ScopeLevel,
    @RecurrenceType, @RecurrenceInterval, @RecurrenceStartDate, @AutoLaunch,
    @CampaignDurationDays, @NextScheduledRun, @IsRecurrencePaused, @IsRecurrenceClone
)";

        using var connection = new SqlConnection(_connectionString);
        await connection.ExecuteAsync(new CommandDefinition(sql, campaign, cancellationToken: cancellationToken)).ConfigureAwait(false);

        _logger.LogMethodExit(nameof(CreateCampaignAsync));
        return campaign;
    }

    public async Task<Campaign?> GetCampaignByIdAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM Campaigns WHERE Id = @Id";
        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstOrDefaultAsync<Campaign>(new CommandDefinition(sql, new { Id = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<Campaign>> GetAllCampaignsAsync(CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM Campaigns ORDER BY CreatedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var campaigns = await connection.QueryAsync<Campaign>(new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return campaigns.ToList();
    }

    public async Task<List<Campaign>> GetCampaignsByStatusAsync(string status, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM Campaigns WHERE Status = @Status ORDER BY CreatedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var campaigns = await connection.QueryAsync<Campaign>(new CommandDefinition(sql, new { Status = status }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return campaigns.ToList();
    }

    public async Task<List<Campaign>> GetActiveCampaignsAsync(CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM Campaigns WHERE Status IN ('InProgress', 'Active') ORDER BY CreatedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var campaigns = await connection.QueryAsync<Campaign>(new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return campaigns.ToList();
    }

    public async Task<List<Campaign>> GetCampaignsByFrameworkAsync(string framework, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM Campaigns WHERE ComplianceFramework = @Framework ORDER BY CreatedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var campaigns = await connection.QueryAsync<Campaign>(new CommandDefinition(sql, new { Framework = framework }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return campaigns.ToList();
    }

    public async Task<bool> UpdateCampaignAsync(Campaign campaign, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE Campaigns SET
    Name = @Name,
    Description = @Description,
    Status = @Status,
    CompletionPercentage = @CompletionPercentage,
    TotalAssignments = @TotalAssignments,
    CompletedAssignments = @CompletedAssignments,
    AssignmentStrategy = @AssignmentStrategy,
    CaseAssigneeId = @CaseAssigneeId,
    CaseAssigneeName = @CaseAssigneeName,
    AssignmentEmailTemplateId = @AssignmentEmailTemplateId,
    ReminderEmailTemplateId = @ReminderEmailTemplateId,
    SourcePolicyId = @SourcePolicyId,
    OwnerId = @OwnerId,
    OwnerName = @OwnerName,
    NotificationCcEmails = @NotificationCcEmails,
    EnableTeamsNotifications = @EnableTeamsNotifications,
    ModifiedBy = @ModifiedBy,
    ModifiedAt = @ModifiedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, campaign, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> UpdateCampaignSettingsAsync(Campaign campaign, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE Campaigns SET
    Name = @Name,
    Description = @Description,
    ReviewPeriodDays = @ReviewPeriodDays,
    DueDate = @DueDate,
    AssignmentStrategy = @AssignmentStrategy,
    CaseAssigneeId = @CaseAssigneeId,
    CaseAssigneeName = @CaseAssigneeName,
    OnDenialAction = @OnDenialAction,
    AutoRemediateOnDenial = @AutoRemediateOnDenial,
    OnIncompleteAction = @OnIncompleteAction,
    OnApprovalAction = @OnApprovalAction,
    ExtensionDays = @ExtensionDays,
    OwnerId = @OwnerId,
    OwnerName = @OwnerName,
    NotificationCcEmails = @NotificationCcEmails,
    EnableTeamsNotifications = @EnableTeamsNotifications,
    AssignmentEmailTemplateId = @AssignmentEmailTemplateId,
    ReminderEmailTemplateId = @ReminderEmailTemplateId,
    ModifiedBy = @ModifiedBy,
    ModifiedAt = @ModifiedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, campaign, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> UpdateCampaignStatusAsync(Guid campaignId, string status, CancellationToken cancellationToken = default)
    {
        const string sql = "UPDATE Campaigns SET Status = @Status, ModifiedAt = @ModifiedAt WHERE Id = @Id";
        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new { Id = campaignId, Status = status, ModifiedAt = DateTime.UtcNow }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> UpdateCampaignStatisticsAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE Campaigns SET
    TotalAssignments = (SELECT COUNT(*) FROM AccessReviewAssignments WHERE CampaignId = @CampaignId),
    CompletedAssignments = (SELECT COUNT(*) FROM AccessReviewAssignments WHERE CampaignId = @CampaignId AND Status IN ('Approved', 'Denied', 'Completed')),
    CompletionPercentage = (
        SELECT CASE
            WHEN COUNT(*) = 0 THEN 0
            ELSE (CAST(COUNT(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 END) AS DECIMAL) / COUNT(*)) * 100
        END
        FROM AccessReviewAssignments WHERE CampaignId = @CampaignId
    ),
    ModifiedAt = @ModifiedAt
WHERE Id = @CampaignId";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new { CampaignId = campaignId, ModifiedAt = DateTime.UtcNow }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<Campaign?> GetStandingCampaignAsync(CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT TOP 1 * FROM Campaigns
WHERE IsRecurring = 1 AND Status = 'Active' AND CampaignType = 'ComplianceReview'
ORDER BY CreatedAt DESC";

        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstOrDefaultAsync<Campaign>(
            new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<Campaign>> GetDueRecurringCampaignsAsync(DateTime today, CancellationToken cancellationToken = default)
    {
        // The recurrence engine looks at parent (non-clone) campaigns whose RecurrenceType
        // is set to a real cadence, are not paused, and whose NextScheduledRun has arrived.
        const string sql = @"
SELECT * FROM Campaigns
WHERE RecurrenceType IS NOT NULL
  AND RecurrenceType <> 'None'
  AND IsRecurrencePaused = 0
  AND IsRecurrenceClone = 0
  AND NextScheduledRun IS NOT NULL
  AND NextScheduledRun <= @Today
  AND Status NOT IN ('Deleted', 'Archived')";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.QueryAsync<Campaign>(
            new CommandDefinition(sql, new { Today = today.Date }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows.ToList();
    }

    public async Task<bool> UpdateRecurrenceTrackingAsync(Guid campaignId, DateTime? nextScheduledRun, bool isRecurrencePaused, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE Campaigns
SET NextScheduledRun = @NextScheduledRun,
    IsRecurrencePaused = @IsRecurrencePaused,
    ModifiedAt = @ModifiedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(
            sql,
            new { Id = campaignId, NextScheduledRun = nextScheduledRun, IsRecurrencePaused = isRecurrencePaused, ModifiedAt = DateTime.UtcNow },
            cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<Campaign?> GetCampaignBySourcePolicyIdAsync(Guid policyId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT TOP 1 * FROM Campaigns
WHERE SourcePolicyId = @PolicyId
  AND Status NOT IN ('Deleted', 'Archived')
ORDER BY CreatedAt DESC";

        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstOrDefaultAsync<Campaign>(
            new CommandDefinition(sql, new { PolicyId = policyId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<AccessReviewAssignment>> GetAssignmentsFilteredAsync(CaseFilterCriteria filter, int limit = 500, CancellationToken cancellationToken = default)
    {
        var sql = @"
SELECT TOP (@Limit) a.*, c.Name as CampaignName
FROM AccessReviewAssignments a
INNER JOIN Campaigns c ON a.CampaignId = c.Id
WHERE c.Status NOT IN ('Deleted', 'Deleting')";

        var parameters = new DynamicParameters();
        parameters.Add("Limit", limit);

        if (filter.CampaignId.HasValue)
        {
            sql += " AND a.CampaignId = @CampaignId";
            parameters.Add("CampaignId", filter.CampaignId.Value);
        }

        if (!string.IsNullOrEmpty(filter.StatusFilter))
        {
            if (filter.StatusFilter == "Overdue")
            {
                sql += " AND a.Status = 'Pending' AND a.DueDate < GETUTCDATE()";
            }
            else
            {
                sql += " AND a.Status = @StatusFilter";
                parameters.Add("StatusFilter", filter.StatusFilter);
            }
        }

        if (filter.NoManagerOnly)
        {
            sql += " AND a.ReviewerId = '00000000-0000-0000-0000-000000000000'";
        }

        if (!string.IsNullOrEmpty(filter.SearchText))
        {
            sql += " AND a.ReviewTargetName LIKE @SearchText";
            parameters.Add("SearchText", "%" + filter.SearchText + "%");
        }

        if (filter.ReviewerId.HasValue)
        {
            sql += " AND a.ReviewerId = @ReviewerId";
            parameters.Add("ReviewerId", filter.ReviewerId.Value);
        }

        sql += " ORDER BY a.AssignedAt DESC";

        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(
            new CommandDefinition(sql, parameters, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<CaseDashboardStats> GetCaseDashboardStatsAsync(CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT
    (SELECT COUNT(*) FROM AccessReviewAssignments a
     INNER JOIN Campaigns c ON a.CampaignId = c.Id
     WHERE a.Status = 'Pending' AND c.Status = 'Active') AS TotalPending,

    (SELECT COUNT(*) FROM AccessReviewAssignments a
     INNER JOIN Campaigns c ON a.CampaignId = c.Id
     WHERE a.Status = 'Pending' AND c.Status = 'Active'
       AND a.ReviewerId = '00000000-0000-0000-0000-000000000000') AS NoManagerCases,

    (SELECT COUNT(*) FROM AccessReviewAssignments a
     INNER JOIN Campaigns c ON a.CampaignId = c.Id
     WHERE a.Status = 'Pending' AND c.Status = 'Active'
       AND a.DueDate < GETUTCDATE()) AS OverdueCases,

    (SELECT COUNT(*) FROM AccessReviewAssignments a
     INNER JOIN Campaigns c ON a.CampaignId = c.Id
     WHERE a.Status IN ('Approved', 'Denied', 'Completed')
       AND CAST(a.CompletedAt AS DATE) = CAST(GETUTCDATE() AS DATE)) AS CompletedToday,

    (SELECT COUNT(*) FROM Campaigns WHERE Status = 'Active') AS ActiveCampaigns";

        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstAsync<CaseDashboardStats>(
            new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<int> BulkUpdateReviewerAsync(List<Guid> assignmentIds, Guid reviewerId, string reviewerName, string? email, CancellationToken cancellationToken = default)
    {
        if (assignmentIds == null || assignmentIds.Count == 0) return 0;

        const string sql = @"
UPDATE AccessReviewAssignments
SET ReviewerId = @ReviewerId,
    ReviewerName = @ReviewerName,
    ReviewerEmail = @ReviewerEmail
WHERE Id IN @Ids AND Status = 'Pending'";

        using var connection = new SqlConnection(_connectionString);
        return await connection.ExecuteAsync(
            new CommandDefinition(sql, new { ReviewerId = reviewerId, ReviewerName = reviewerName, ReviewerEmail = email, Ids = assignmentIds }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<bool> DeleteCampaignAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = "UPDATE Campaigns SET Status = 'Deleted', ModifiedAt = @ModifiedAt WHERE Id = @Id";
        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new { Id = campaignId, ModifiedAt = DateTime.UtcNow }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> HardDeleteCampaignAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        _logger.LogMethodEntry(nameof(HardDeleteCampaignAsync), new { campaignId });

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);
        using var transaction = connection.BeginTransaction();

        try
        {
            // First, set campaign status to 'Deleting' for audit trail
            const string updateStatusSql = "UPDATE Campaigns SET Status = 'Deleting', ModifiedAt = @ModifiedAt WHERE Id = @Id";
            await connection.ExecuteAsync(new CommandDefinition(updateStatusSql, new { Id = campaignId, ModifiedAt = DateTime.UtcNow }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);

            // Delete all related records in order (to respect foreign keys)

            // 1. Delete remediation actions (table may not exist yet)
            var remediationRows = 0;
            try
            {
                const string deleteRemediationSql = "DELETE FROM RemediationActions WHERE CampaignId = @CampaignId";
                remediationRows = await connection.ExecuteAsync(new CommandDefinition(deleteRemediationSql, new { CampaignId = campaignId }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
                _logger.LogInformation("Deleted {Count} remediation actions for campaign {CampaignId}", remediationRows, campaignId);
            }
            catch (SqlException ex) when (ex.Message.Contains("Invalid object name"))
            {
                _logger.LogDebug("RemediationActions table does not exist, skipping");
            }

            // 2. Delete decision history (via AssignmentId since ReviewDecisionHistory doesn't have CampaignId)
            const string deleteHistorySql = @"
                DELETE FROM ReviewDecisionHistory
                WHERE AssignmentId IN (
                    SELECT Id FROM AccessReviewAssignments WHERE CampaignId = @CampaignId
                )";
            var historyRows = await connection.ExecuteAsync(new CommandDefinition(deleteHistorySql, new { CampaignId = campaignId }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
            _logger.LogInformation("Deleted {Count} decision history records for campaign {CampaignId}", historyRows, campaignId);

            // 3. Delete assignments
            const string deleteAssignmentsSql = "DELETE FROM AccessReviewAssignments WHERE CampaignId = @CampaignId";
            var assignmentRows = await connection.ExecuteAsync(new CommandDefinition(deleteAssignmentsSql, new { CampaignId = campaignId }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);
            _logger.LogInformation("Deleted {Count} assignments for campaign {CampaignId}", assignmentRows, campaignId);

            // 4. Finally, delete the campaign itself
            const string deleteCampaignSql = "DELETE FROM Campaigns WHERE Id = @Id";
            var campaignRows = await connection.ExecuteAsync(new CommandDefinition(deleteCampaignSql, new { Id = campaignId }, transaction, cancellationToken: cancellationToken)).ConfigureAwait(false);

            transaction.Commit();

            _logger.LogInformation("Hard deleted campaign {CampaignId} - Removed {AssignmentCount} assignments, {HistoryCount} history records, {RemediationCount} remediation actions",
                campaignId, assignmentRows, historyRows, remediationRows);

            return campaignRows > 0;
        }
        catch (Exception ex)
        {
            transaction.Rollback();
            _logger.LogError(ex, "Error hard deleting campaign {CampaignId}", campaignId);
            throw;
        }
        finally
        {
            _logger.LogMethodExit(nameof(HardDeleteCampaignAsync));
        }
    }

    // ========================================
    // ASSIGNMENT OPERATIONS
    // ========================================

    public async Task<AccessReviewAssignment> CreateAssignmentAsync(AccessReviewAssignment assignment, CancellationToken cancellationToken = default)
    {
        const string sql = @"
INSERT INTO AccessReviewAssignments (
    Id, CampaignId, ReviewerId, ReviewerEmail, ReviewerName,
    ReviewTargetId, ReviewTargetType, ReviewTargetName,
    ContextData, RiskScore, RiskLevel, LastAccessDate, AccessFrequency, ReasonForAccess,
    Status, AssignedAt, DueDate, RemindersSent,
    IsDelegated, DelegatedTo, DelegatedAt, DelegationReason,
    IsEscalated, EscalatedTo, EscalatedAt, EscalationReason
) VALUES (
    @Id, @CampaignId, @ReviewerId, @ReviewerEmail, @ReviewerName,
    @ReviewTargetId, @ReviewTargetType, @ReviewTargetName,
    @ContextData, @RiskScore, @RiskLevel, @LastAccessDate, @AccessFrequency, @ReasonForAccess,
    @Status, @AssignedAt, @DueDate, @RemindersSent,
    @IsDelegated, @DelegatedTo, @DelegatedAt, @DelegationReason,
    @IsEscalated, @EscalatedTo, @EscalatedAt, @EscalationReason
)";

        using var connection = new SqlConnection(_connectionString);
        await connection.ExecuteAsync(new CommandDefinition(sql, assignment, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignment;
    }

    public async Task<int> CreateAssignmentsBulkAsync(List<AccessReviewAssignment> assignments, CancellationToken cancellationToken = default)
    {
        _logger.LogMethodEntry(nameof(CreateAssignmentsBulkAsync), new { count = assignments.Count });

        const string sql = @"
INSERT INTO AccessReviewAssignments (
    Id, CampaignId, ReviewerId, ReviewerEmail, ReviewerName,
    ReviewTargetId, ReviewTargetType, ReviewTargetName,
    ContextData, RiskScore, RiskLevel, LastAccessDate, AccessFrequency, ReasonForAccess,
    Status, AssignedAt, DueDate, RemindersSent,
    IsDelegated, DelegatedTo, DelegatedAt, DelegationReason,
    IsEscalated, EscalatedTo, EscalatedAt, EscalationReason
) VALUES (
    @Id, @CampaignId, @ReviewerId, @ReviewerEmail, @ReviewerName,
    @ReviewTargetId, @ReviewTargetType, @ReviewTargetName,
    @ContextData, @RiskScore, @RiskLevel, @LastAccessDate, @AccessFrequency, @ReasonForAccess,
    @Status, @AssignedAt, @DueDate, @RemindersSent,
    @IsDelegated, @DelegatedTo, @DelegatedAt, @DelegationReason,
    @IsEscalated, @EscalatedTo, @EscalatedAt, @EscalationReason
)";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, assignments, cancellationToken: cancellationToken)).ConfigureAwait(false);

        _logger.LogMethodExit(nameof(CreateAssignmentsBulkAsync));
        return rows;
    }

    public async Task<AccessReviewAssignment?> GetAssignmentByIdAsync(Guid assignmentId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM AccessReviewAssignments WHERE Id = @Id";
        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstOrDefaultAsync<AccessReviewAssignment>(new CommandDefinition(sql, new { Id = assignmentId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<AccessReviewAssignment>> GetCampaignAssignmentsAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM AccessReviewAssignments WHERE CampaignId = @CampaignId ORDER BY AssignedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(new CommandDefinition(sql, new { CampaignId = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<List<AccessReviewAssignment>> GetAssignmentsByReviewerAsync(Guid reviewerId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM AccessReviewAssignments WHERE ReviewerId = @ReviewerId ORDER BY DueDate";
        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(new CommandDefinition(sql, new { ReviewerId = reviewerId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<List<AccessReviewAssignment>> GetAssignmentsByTargetAsync(Guid reviewTargetId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT a.*, c.Name AS CampaignName
FROM AccessReviewAssignments a
INNER JOIN Campaigns c ON a.CampaignId = c.Id
WHERE a.ReviewTargetId = @ReviewTargetId
  AND a.Status IN ('Pending', 'InProgress')
  AND c.Status NOT IN ('Deleted', 'Archived')
ORDER BY a.DueDate ASC";

        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(
            new CommandDefinition(sql, new { ReviewTargetId = reviewTargetId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<DateTime?> GetLastReviewedDateForTargetAsync(Guid reviewTargetId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT MAX(CompletedAt)
FROM AccessReviewAssignments
WHERE ReviewTargetId = @ReviewTargetId
  AND CompletedAt IS NOT NULL";

        using var connection = new SqlConnection(_connectionString);
        return await connection.ExecuteScalarAsync<DateTime?>(
            new CommandDefinition(sql, new { ReviewTargetId = reviewTargetId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<AccessReviewAssignment>> GetAssignmentsByStatusAsync(Guid campaignId, string status, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM AccessReviewAssignments WHERE CampaignId = @CampaignId AND Status = @Status ORDER BY AssignedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(new CommandDefinition(sql, new { CampaignId = campaignId, Status = status }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<List<AccessReviewAssignment>> GetAllPendingAssignmentsAsync(int maxResults = 100, CancellationToken cancellationToken = default)
    {
        // First, let's see what's in the tables for debugging
        const string debugSql = @"
SELECT
    (SELECT COUNT(*) FROM AccessReviewAssignments) as TotalAssignments,
    (SELECT COUNT(*) FROM AccessReviewAssignments WHERE Status = 'Pending') as PendingAssignments,
    (SELECT COUNT(*) FROM Campaigns WHERE Status = 'Active') as ActiveCampaigns";

        const string sql = @"
SELECT TOP (@MaxResults) a.*
FROM AccessReviewAssignments a
INNER JOIN Campaigns c ON a.CampaignId = c.Id
WHERE a.Status = 'Pending'
  AND c.Status = 'Active'
ORDER BY a.DueDate ASC, a.AssignedAt DESC";

        using var connection = new SqlConnection(_connectionString);

        // Log debug info
        try
        {
            var debug = await connection.QueryFirstOrDefaultAsync<dynamic>(new CommandDefinition(debugSql, cancellationToken: cancellationToken)).ConfigureAwait(false);
            _logger.LogInformation("GetAllPendingAssignmentsAsync - Debug: TotalAssignments={Total}, PendingAssignments={Pending}, ActiveCampaigns={Active}",
                debug?.TotalAssignments, debug?.PendingAssignments, debug?.ActiveCampaigns);
        }
        catch (Exception ex) { _logger.LogWarning(ex, "Non-critical debug query failed in GetAllPendingAssignmentsAsync"); }

        var assignments = await connection.QueryAsync<AccessReviewAssignment>(
            new CommandDefinition(sql, new { MaxResults = maxResults }, cancellationToken: cancellationToken)).ConfigureAwait(false);

        _logger.LogInformation("GetAllPendingAssignmentsAsync - Returning {Count} assignments", assignments.Count());
        return assignments.ToList();
    }

    public async Task<List<AccessReviewAssignment>> GetAllAssignmentsAsync(int maxResults = 200, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT TOP (@MaxResults) a.*, c.Name as CampaignName
FROM AccessReviewAssignments a
INNER JOIN Campaigns c ON a.CampaignId = c.Id
WHERE c.Status NOT IN ('Deleted', 'Deleting')
ORDER BY a.AssignedAt DESC";

        using var connection = new SqlConnection(_connectionString);
        var assignments = await connection.QueryAsync<AccessReviewAssignment>(
            new CommandDefinition(sql, new { MaxResults = maxResults }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return assignments.ToList();
    }

    public async Task<bool> UpdateAssignmentAsync(AccessReviewAssignment assignment, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE AccessReviewAssignments SET
    Status = @Status,
    Decision = @Decision,
    Justification = @Justification,
    Comments = @Comments,
    CompletedAt = @CompletedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, assignment, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> UpdateAssignmentDecisionAsync(Guid assignmentId, string decision, string? justification, Guid decisionMakerId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE AccessReviewAssignments SET
    Status = 'Completed',
    Decision = @Decision,
    Justification = @Justification,
    CompletedAt = @CompletedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new
        {
            Id = assignmentId,
            Decision = decision,
            Justification = justification,
            CompletedAt = DateTime.UtcNow
        }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> DelegateAssignmentAsync(Guid assignmentId, Guid delegateTo, string reason, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE AccessReviewAssignments SET
    IsDelegated = 1,
    DelegatedTo = @DelegatedTo,
    DelegatedAt = @DelegatedAt,
    DelegationReason = @Reason
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new
        {
            Id = assignmentId,
            DelegatedTo = delegateTo,
            DelegatedAt = DateTime.UtcNow,
            Reason = reason
        }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    public async Task<bool> EscalateAssignmentAsync(Guid assignmentId, Guid escalateTo, string reason, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE AccessReviewAssignments SET
    IsEscalated = 1,
    EscalatedTo = @EscalatedTo,
    EscalatedAt = @EscalatedAt,
    EscalationReason = @Reason
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new
        {
            Id = assignmentId,
            EscalatedTo = escalateTo,
            EscalatedAt = DateTime.UtcNow,
            Reason = reason
        }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    // ========================================
    // DECISION HISTORY OPERATIONS
    // ========================================

    public async Task<ReviewDecisionHistory> RecordDecisionAsync(ReviewDecisionHistory decision, CancellationToken cancellationToken = default)
    {
        const string sql = @"
INSERT INTO ReviewDecisionHistory (
    Id, AssignmentId, CampaignId,
    Decision, PreviousDecision, Justification, Comments,
    DecisionMakerId, DecisionMakerName, DecisionMakerEmail,
    DecisionDate, IpAddress, UserAgent, DecisionContext,
    RiskScoreAtDecision, RiskLevelAtDecision, ComplianceFramework,
    WasEscalated, WasDelegated
) VALUES (
    @Id, @AssignmentId, @CampaignId,
    @Decision, @PreviousDecision, @Justification, @Comments,
    @DecisionMakerId, @DecisionMakerName, @DecisionMakerEmail,
    @DecisionDate, @IpAddress, @UserAgent, @DecisionContext,
    @RiskScoreAtDecision, @RiskLevelAtDecision, @ComplianceFramework,
    @WasEscalated, @WasDelegated
)";

        using var connection = new SqlConnection(_connectionString);
        await connection.ExecuteAsync(new CommandDefinition(sql, decision, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return decision;
    }

    public async Task<List<ReviewDecisionHistory>> GetAssignmentHistoryAsync(Guid assignmentId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM ReviewDecisionHistory WHERE AssignmentId = @AssignmentId ORDER BY DecisionDate DESC";
        using var connection = new SqlConnection(_connectionString);
        var history = await connection.QueryAsync<ReviewDecisionHistory>(new CommandDefinition(sql, new { AssignmentId = assignmentId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return history.ToList();
    }

    public async Task<List<ReviewDecisionHistory>> GetCampaignHistoryAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM ReviewDecisionHistory WHERE CampaignId = @CampaignId ORDER BY DecisionDate DESC";
        using var connection = new SqlConnection(_connectionString);
        var history = await connection.QueryAsync<ReviewDecisionHistory>(new CommandDefinition(sql, new { CampaignId = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return history.ToList();
    }

    // ========================================
    // REMEDIATION OPERATIONS
    // ========================================

    public async Task<RemediationAction> CreateRemediationActionAsync(RemediationAction action, CancellationToken cancellationToken = default)
    {
        const string sql = @"
INSERT INTO RemediationActions (
    Id, AssignmentId, CampaignId, DecisionHistoryId,
    ActionType, ActionDescription, ActionParameters,
    TargetEntityId, TargetEntityType,
    Status, ScheduledFor, RequiresApproval,
    CreatedAt, CreatedBy, RetryCount
) VALUES (
    @Id, @AssignmentId, @CampaignId, @DecisionHistoryId,
    @ActionType, @ActionDescription, @ActionParameters,
    @TargetEntityId, @TargetEntityType,
    @Status, @ScheduledFor, @RequiresApproval,
    @CreatedAt, @CreatedBy, @RetryCount
)";

        using var connection = new SqlConnection(_connectionString);
        await connection.ExecuteAsync(new CommandDefinition(sql, action, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return action;
    }

    public async Task<List<RemediationAction>> GetPendingRemediationActionsAsync(CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM RemediationActions WHERE Status = 'Pending' ORDER BY ScheduledFor";
        using var connection = new SqlConnection(_connectionString);
        var actions = await connection.QueryAsync<RemediationAction>(new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return actions.ToList();
    }

    public async Task<List<RemediationAction>> GetCampaignRemediationActionsAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM RemediationActions WHERE CampaignId = @CampaignId ORDER BY CreatedAt DESC";
        using var connection = new SqlConnection(_connectionString);
        var actions = await connection.QueryAsync<RemediationAction>(new CommandDefinition(sql, new { CampaignId = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return actions.ToList();
    }

    public async Task<bool> UpdateRemediationActionStatusAsync(Guid actionId, string status, string? result, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE RemediationActions SET
    Status = @Status,
    ExecutionResult = @Result,
    ExecutedAt = @ExecutedAt
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, new
        {
            Id = actionId,
            Status = status,
            Result = result,
            ExecutedAt = DateTime.UtcNow
        }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    // ========================================
    // TEMPLATE OPERATIONS
    // ========================================

    public async Task<List<CampaignTemplate>> GetActiveTemplatesAsync(CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM CampaignTemplates WHERE IsActive = 1 ORDER BY Name";
        using var connection = new SqlConnection(_connectionString);
        var templates = await connection.QueryAsync<CampaignTemplate>(new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return templates.ToList();
    }

    public async Task<CampaignTemplate?> GetTemplateByIdAsync(Guid templateId, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM CampaignTemplates WHERE Id = @Id";
        using var connection = new SqlConnection(_connectionString);
        return await connection.QueryFirstOrDefaultAsync<CampaignTemplate>(new CommandDefinition(sql, new { Id = templateId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    public async Task<List<CampaignTemplate>> GetTemplatesByFrameworkAsync(string framework, CancellationToken cancellationToken = default)
    {
        const string sql = "SELECT * FROM CampaignTemplates WHERE ComplianceFramework = @Framework AND IsActive = 1 ORDER BY Name";
        using var connection = new SqlConnection(_connectionString);
        var templates = await connection.QueryAsync<CampaignTemplate>(new CommandDefinition(sql, new { Framework = framework }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return templates.ToList();
    }

    public async Task<CampaignTemplate> CreateTemplateAsync(CampaignTemplate template, CancellationToken cancellationToken = default)
    {
        const string sql = @"
INSERT INTO CampaignTemplates (
    Id, Name, Description, TemplateType, ComplianceFramework,
    DefaultConfiguration, ScopeConfiguration, NotificationConfiguration,
    DefaultReviewPeriodDays, RecurrencePattern,
    IsBuiltIn, IsActive, UsageCount,
    CreatedAt, CreatedBy
) VALUES (
    @Id, @Name, @Description, @TemplateType, @ComplianceFramework,
    @DefaultConfiguration, @ScopeConfiguration, @NotificationConfiguration,
    @DefaultReviewPeriodDays, @RecurrencePattern,
    @IsBuiltIn, @IsActive, @UsageCount,
    @CreatedAt, @CreatedBy
)";

        using var connection = new SqlConnection(_connectionString);
        await connection.ExecuteAsync(new CommandDefinition(sql, template, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return template;
    }

    public async Task<bool> UpdateTemplateAsync(CampaignTemplate template, CancellationToken cancellationToken = default)
    {
        const string sql = @"
UPDATE CampaignTemplates SET
    Name = @Name,
    Description = @Description,
    DefaultConfiguration = @DefaultConfiguration,
    ModifiedAt = @ModifiedAt,
    ModifiedBy = @ModifiedBy
WHERE Id = @Id";

        using var connection = new SqlConnection(_connectionString);
        var rows = await connection.ExecuteAsync(new CommandDefinition(sql, template, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return rows > 0;
    }

    // ========================================
    // STATISTICS & REPORTING
    // ========================================

    public async Task<CampaignStatistics> GetCampaignStatisticsAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT
    @CampaignId AS CampaignId,
    COUNT(*) AS TotalAssignments,
    SUM(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 ELSE 0 END) AS CompletedAssignments,
    SUM(CASE WHEN Status = 'Pending' THEN 1 ELSE 0 END) AS PendingAssignments,
    SUM(CASE WHEN Status = 'Pending' AND DueDate < GETUTCDATE() THEN 1 ELSE 0 END) AS OverdueAssignments,
    SUM(CASE WHEN Decision = 'Approved' THEN 1 ELSE 0 END) AS ApprovedCount,
    SUM(CASE WHEN Decision = 'Denied' THEN 1 ELSE 0 END) AS DeniedCount,
    CASE
        WHEN COUNT(*) = 0 THEN 0
        ELSE (CAST(SUM(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 ELSE 0 END) AS DECIMAL) / COUNT(*)) * 100
    END AS CompletionPercentage,
    ISNULL(DATEDIFF(day, GETUTCDATE(), (SELECT DueDate FROM Campaigns WHERE Id = @CampaignId)), 0) AS DaysRemaining
FROM AccessReviewAssignments
WHERE CampaignId = @CampaignId";

        using var connection = new SqlConnection(_connectionString);
        var stats = await connection.QueryFirstOrDefaultAsync<CampaignStatistics>(new CommandDefinition(sql, new { CampaignId = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return stats ?? new CampaignStatistics { CampaignId = campaignId };
    }

    public async Task<List<ReviewerWorkload>> GetReviewerWorkloadAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT
    ReviewerId,
    ReviewerName,
    COUNT(*) AS TotalAssigned,
    SUM(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 ELSE 0 END) AS Completed,
    SUM(CASE WHEN Status = 'Pending' THEN 1 ELSE 0 END) AS Pending,
    CASE
        WHEN COUNT(*) = 0 THEN 0
        ELSE (CAST(SUM(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 ELSE 0 END) AS DECIMAL) / COUNT(*)) * 100
    END AS CompletionPercentage
FROM AccessReviewAssignments
WHERE CampaignId = @CampaignId
GROUP BY ReviewerId, ReviewerName";

        using var connection = new SqlConnection(_connectionString);
        var workload = await connection.QueryAsync<ReviewerWorkload>(new CommandDefinition(sql, new { CampaignId = campaignId }, cancellationToken: cancellationToken)).ConfigureAwait(false);
        return workload.ToList();
    }

    public async Task<int> GetOverdueAssignmentsCountAsync(Guid campaignId, CancellationToken cancellationToken = default)
    {
        const string sql = @"
SELECT COUNT(*)
FROM AccessReviewAssignments
WHERE CampaignId = @CampaignId
  AND Status = 'Pending'
  AND DueDate < GETUTCDATE()";

        using var connection = new SqlConnection(_connectionString);
        return await connection.ExecuteScalarAsync<int>(sql, new { CampaignId = campaignId }).ConfigureAwait(false);
    }

    // ========================================
    // SETTINGS OPERATIONS
    // ========================================

    public async Task<AccessReviewSettings> GetSettingsAsync(CancellationToken cancellationToken = default)
    {
        _logger.LogMethodEntry(nameof(GetSettingsAsync));

        const string sql = @"
SELECT * FROM AccessReviewSettings
WHERE Id = '00000000-0000-0000-0000-000000000001'";

        using var connection = new SqlConnection(_connectionString);
        var settings = await connection.QueryFirstOrDefaultAsync<AccessReviewSettings>(new CommandDefinition(sql, cancellationToken: cancellationToken)).ConfigureAwait(false);

        // If no settings exist, create default settings
        if (settings == null)
        {
            _logger.LogWarning("AccessReviewSettings not found, creating default settings");
            settings = new AccessReviewSettings
            {
                Id = new Guid("00000000-0000-0000-0000-000000000001"),
                DefaultReviewPeriodDays = 14,
                DefaultReminderFrequencyDays = 3,
                RequireJustification = true,
                EnableNotifications = true,
                AutoRevokeOnExpiry = false,
                AllowBulkApproval = false,
                EscalationDays = 7,
                HighRiskReviewFrequency = "Monthly",
                GroupReviewFrequency = "Quarterly",
                CreatedBy = "System",
                CreatedAt = DateTime.UtcNow
            };

            // Insert default settings
            const string insertSql = @"
INSERT INTO AccessReviewSettings (
    Id, DefaultReviewPeriodDays, DefaultReminderFrequencyDays,
    RequireJustification, EnableNotifications, AutoRevokeOnExpiry,
    AllowBulkApproval, DefaultComplianceFramework, EscalationDays,
    AutoCreatePolicyReviews, AutoReviewNewUsers, NewUserReviewDays,
    AutoReviewHighRisk, HighRiskReviewFrequency,
    AutoReviewGroupMemberships, GroupReviewFrequency,
    NotificationFromEmail, NotificationFromName,
    CreatedBy, CreatedAt
) VALUES (
    @Id, @DefaultReviewPeriodDays, @DefaultReminderFrequencyDays,
    @RequireJustification, @EnableNotifications, @AutoRevokeOnExpiry,
    @AllowBulkApproval, @DefaultComplianceFramework, @EscalationDays,
    @AutoCreatePolicyReviews, @AutoReviewNewUsers, @NewUserReviewDays,
    @AutoReviewHighRisk, @HighRiskReviewFrequency,
    @AutoReviewGroupMemberships, @GroupReviewFrequency,
    @NotificationFromEmail, @NotificationFromName,
    @CreatedBy, @CreatedAt
)";

            await connection.ExecuteAsync(new CommandDefinition(insertSql, settings, cancellationToken: cancellationToken)).ConfigureAwait(false);
            _logger.LogInformation("Default AccessReviewSettings created");
        }

        return settings;
    }

    public async Task<bool> UpdateSettingsAsync(AccessReviewSettings settings, CancellationToken cancellationToken = default)
    {
        _logger.LogMethodEntry(nameof(UpdateSettingsAsync));

        const string sql = @"
UPDATE AccessReviewSettings
SET
    DefaultReviewPeriodDays = @DefaultReviewPeriodDays,
    DefaultReminderFrequencyDays = @DefaultReminderFrequencyDays,
    RequireJustification = @RequireJustification,
    EnableNotifications = @EnableNotifications,
    AutoRevokeOnExpiry = @AutoRevokeOnExpiry,
    AllowBulkApproval = @AllowBulkApproval,
    DefaultComplianceFramework = @DefaultComplianceFramework,
    EscalationDays = @EscalationDays,
    AutoCreatePolicyReviews = @AutoCreatePolicyReviews,
    AutoReviewNewUsers = @AutoReviewNewUsers,
    NewUserReviewDays = @NewUserReviewDays,
    AutoReviewHighRisk = @AutoReviewHighRisk,
    HighRiskReviewFrequency = @HighRiskReviewFrequency,
    AutoReviewGroupMemberships = @AutoReviewGroupMemberships,
    GroupReviewFrequency = @GroupReviewFrequency,
    NotificationFromEmail = @NotificationFromEmail,
    NotificationFromName = @NotificationFromName,
    NotificationSubjectTemplate = @NotificationSubjectTemplate,
    NotificationBodyTemplate = @NotificationBodyTemplate,
    DefaultCampaignOwnerId = @DefaultCampaignOwnerId,
    DefaultCampaignOwnerName = @DefaultCampaignOwnerName,
    DefaultNotificationCcEmails = @DefaultNotificationCcEmails,
    ModifiedAt = GETUTCDATE(),
    ModifiedBy = @ModifiedBy
WHERE Id = '00000000-0000-0000-0000-000000000001'";

        using var connection = new SqlConnection(_connectionString);
        var rowsAffected = await connection.ExecuteAsync(new CommandDefinition(sql, settings, cancellationToken: cancellationToken)).ConfigureAwait(false);

        _logger.LogInformation("AccessReviewSettings updated, rows affected: {RowsAffected}", rowsAffected);
        return rowsAffected > 0;
    }
}
