using Dapper;
using DataAccessLibrary.Models;
using Logging;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace DataAccessLibrary.Repositories;

/// <summary>
/// Dapper-based implementation of <see cref="IVirtualContainerRepository"/>.
/// Schema managed by V055__VirtualContainers.sql.
/// </summary>
public class VirtualContainerRepository : IVirtualContainerRepository
{
    private readonly string _connectionString;
    private readonly IGlobalLogger _logger;

    public VirtualContainerRepository(IConfiguration configuration, IGlobalLogger logger)
    {
        _connectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    private SqlConnection CreateConnection() => new SqlConnection(_connectionString);

    // -------------------------------------------------------------------------
    // Read
    // -------------------------------------------------------------------------

    public async Task<List<VirtualContainer>> GetContainersForConnectionAsync(
        Guid connectionId, CancellationToken ct = default)
    {
        const string sql = @"
            SELECT Id, ConnectionId, Name, ParentId, ContainerType,
                   AttributeName, AttributeValue, RuleExpression,
                   IconClass, SortOrder, IsAutoGenerated, IsActive,
                   CreatedAt, ModifiedAt
            FROM   VirtualContainers
            WHERE  ConnectionId = @ConnectionId
              AND  IsActive = 1
            ORDER BY SortOrder, Name;";

        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        var rows = await conn.QueryAsync<VirtualContainer>(sql, new { ConnectionId = connectionId });
        return rows.ToList();
    }

    public async Task<VirtualContainer?> GetContainerAsync(Guid id, CancellationToken ct = default)
    {
        const string sql = @"
            SELECT Id, ConnectionId, Name, ParentId, ContainerType,
                   AttributeName, AttributeValue, RuleExpression,
                   IconClass, SortOrder, IsAutoGenerated, IsActive,
                   CreatedAt, ModifiedAt
            FROM   VirtualContainers
            WHERE  Id = @Id;";

        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        return await conn.QuerySingleOrDefaultAsync<VirtualContainer>(sql, new { Id = id });
    }

    // -------------------------------------------------------------------------
    // Write
    // -------------------------------------------------------------------------

    public async Task<Guid> CreateContainerAsync(VirtualContainer container, CancellationToken ct = default)
    {
        if (container.Id == Guid.Empty) container.Id = Guid.NewGuid();
        container.CreatedAt = DateTime.UtcNow;
        container.ModifiedAt = null;

        const string sql = @"
            INSERT INTO VirtualContainers
                (Id, ConnectionId, Name, ParentId, ContainerType,
                 AttributeName, AttributeValue, RuleExpression,
                 IconClass, SortOrder, IsAutoGenerated, IsActive, CreatedAt, ModifiedAt)
            VALUES
                (@Id, @ConnectionId, @Name, @ParentId, @ContainerType,
                 @AttributeName, @AttributeValue, @RuleExpression,
                 @IconClass, @SortOrder, @IsAutoGenerated, @IsActive, @CreatedAt, @ModifiedAt);";

        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        await conn.ExecuteAsync(sql, container);
        return container.Id;
    }

    public async Task UpdateContainerAsync(VirtualContainer container, CancellationToken ct = default)
    {
        container.ModifiedAt = DateTime.UtcNow;

        const string sql = @"
            UPDATE VirtualContainers
            SET  Name           = @Name,
                 ParentId       = @ParentId,
                 ContainerType  = @ContainerType,
                 AttributeName  = @AttributeName,
                 AttributeValue = @AttributeValue,
                 RuleExpression = @RuleExpression,
                 IconClass      = @IconClass,
                 SortOrder      = @SortOrder,
                 IsActive       = @IsActive,
                 ModifiedAt     = @ModifiedAt
            WHERE Id = @Id;";

        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        await conn.ExecuteAsync(sql, container);
    }

    public async Task DeleteContainerAsync(Guid id, CancellationToken ct = default)
    {
        const string sql = "DELETE FROM VirtualContainers WHERE Id = @Id;";
        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        await conn.ExecuteAsync(sql, new { Id = id });
    }

    // -------------------------------------------------------------------------
    // Auto-discovery
    // -------------------------------------------------------------------------

    public async Task<int> AutoDiscoverContainersAsync(Guid connectionId, CancellationToken ct = default)
    {
        using var conn = CreateConnection();
        await conn.OpenAsync(ct);

        // The stored proc returns a single row with ContainersCreated
        var result = await conn.QuerySingleOrDefaultAsync<int>(
            "EXEC dbo.usp_AutoDiscoverVirtualContainers @ConnectionId",
            new { ConnectionId = connectionId });

        _logger.LogInformation("VirtualContainerRepository.AutoDiscoverContainersAsync: {Count} containers created for connection {ConnectionId}", result, connectionId);
        return result;
    }

    // -------------------------------------------------------------------------
    // Object count
    // -------------------------------------------------------------------------

    public async Task<int> GetObjectCountForContainerAsync(
        VirtualContainer container, CancellationToken ct = default)
    {
        string sql;
        object parameters;

        switch (container.ContainerType)
        {
            case "ObjectClass":
                sql = @"SELECT COUNT(*) FROM Objects
                        WHERE SourceConnectionId = @ConnId
                          AND ObjectClass = @AttrValue;";
                parameters = new { ConnId = container.ConnectionId, AttrValue = container.AttributeValue };
                break;

            case "Attribute":
                // Build a safe parameterized query. AttributeName is admin-controlled
                // (never end-user input) so we validate against a known allow-list.
                var allowedColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
                {
                    "Department", "Company", "Office", "EmployeeType",
                    "Division", "City", "State", "Country", "JobTitle"
                };

                if (string.IsNullOrEmpty(container.AttributeName) ||
                    !allowedColumns.Contains(container.AttributeName))
                {
                    _logger.LogWarning("VirtualContainerRepository: Unknown AttributeName '{AttributeName}' — returning 0", container.AttributeName);
                    return 0;
                }

                // Safe: column name is validated against allow-list above
                sql = $@"SELECT COUNT(*) FROM Objects
                         WHERE SourceConnectionId = @ConnId
                           AND [{container.AttributeName}] = @AttrValue;";
                parameters = new { ConnId = container.ConnectionId, AttrValue = container.AttributeValue };
                break;

            default:
                _logger.LogWarning("VirtualContainerRepository: Unsupported ContainerType '{ContainerType}' for count — returning 0", container.ContainerType);
                return 0;
        }

        using var conn = CreateConnection();
        await conn.OpenAsync(ct);
        return await conn.ExecuteScalarAsync<int>(sql, parameters);
    }
}
