-- ========================================
-- Access Review Campaign Tables
-- Manual Migration Script
-- ========================================

USE IdentityCenter;
GO

-- Campaigns Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Campaigns')
BEGIN
    CREATE TABLE [Campaigns] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [Name] nvarchar(200) NOT NULL,
        [Description] nvarchar(max) NULL,
        [CampaignType] nvarchar(50) NOT NULL,
        [ReviewType] nvarchar(50) NULL,
        [ConnectionScope] nvarchar(max) NULL,
        [ObjectClassFilter] nvarchar(100) NULL,
        [DepartmentFilter] nvarchar(max) NULL,
        [RiskLevelFilter] nvarchar(50) NULL,
        [PolicyViolationFilter] bit NOT NULL,
        [CustomScopeFilter] nvarchar(max) NULL,
        [IncludeNestedMemberships] bit NOT NULL,
        [MaxNestedDepth] int NOT NULL,
        [SelectedPolicyIds] nvarchar(max) NULL,
        [StartDate] datetime2 NOT NULL,
        [EndDate] datetime2 NOT NULL,
        [DueDate] datetime2 NULL,
        [ReviewPeriodDays] int NOT NULL,
        [Status] nvarchar(50) NOT NULL,
        [CompletionPercentage] decimal(5,2) NOT NULL,
        [TotalAssignments] int NOT NULL,
        [CompletedAssignments] int NOT NULL,
        [AutoGenerated] bit NOT NULL,
        [SourcePolicyExecutionId] uniqueidentifier NULL,
        [ParentCampaignId] uniqueidentifier NULL,
        [IsRecurring] bit NOT NULL,
        [RecurrencePattern] nvarchar(max) NULL,
        [AssignmentStrategy] nvarchar(50) NULL,
        [NotificationSettings] nvarchar(max) NULL,
        [EscalationSettings] nvarchar(max) NULL,
        [EnableNotifications] bit NOT NULL,
        [ReminderDaysBefore] int NOT NULL,
        [CreatedBy] nvarchar(256) NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [ModifiedBy] nvarchar(256) NULL,
        [ModifiedAt] datetime2 NULL,
        [ComplianceFramework] nvarchar(100) NULL
    );
    PRINT 'Created Campaigns table';
END
ELSE
BEGIN
    PRINT 'Campaigns table already exists';
END
GO

-- AccessReviewAssignments Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AccessReviewAssignments')
BEGIN
    CREATE TABLE [AccessReviewAssignments] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [CampaignId] uniqueidentifier NOT NULL,
        [ReviewerId] uniqueidentifier NOT NULL,
        [ReviewerEmail] nvarchar(256) NULL,
        [ReviewerName] nvarchar(200) NULL,
        [ReviewTargetId] uniqueidentifier NOT NULL,
        [ReviewTargetType] nvarchar(50) NOT NULL,
        [ReviewTargetName] nvarchar(200) NULL,
        [ContextData] nvarchar(max) NULL,
        [RiskScore] int NOT NULL,
        [RiskLevel] nvarchar(50) NULL,
        [LastAccessDate] datetime2 NULL,
        [AccessFrequency] nvarchar(50) NULL,
        [ReasonForAccess] nvarchar(max) NULL,
        [Status] nvarchar(50) NOT NULL,
        [AssignedAt] datetime2 NOT NULL,
        [DueDate] datetime2 NULL,
        [CompletedAt] datetime2 NULL,
        [Decision] nvarchar(50) NULL,
        [Justification] nvarchar(max) NULL,
        [Comments] nvarchar(max) NULL,
        [IsDelegated] bit NOT NULL,
        [DelegatedTo] uniqueidentifier NULL,
        [DelegatedAt] datetime2 NULL,
        [DelegationReason] nvarchar(max) NULL,
        [IsEscalated] bit NOT NULL,
        [EscalatedTo] uniqueidentifier NULL,
        [EscalatedAt] datetime2 NULL,
        [EscalationReason] nvarchar(max) NULL,
        [RemindersSent] int NOT NULL,
        [LastReminderSent] datetime2 NULL,
        [IpAddress] nvarchar(max) NULL,
        [UserAgent] nvarchar(max) NULL,
        CONSTRAINT [FK_AccessReviewAssignments_Campaigns] FOREIGN KEY ([CampaignId])
            REFERENCES [Campaigns]([Id]) ON DELETE CASCADE
    );

    CREATE INDEX [IX_AccessReviewAssignments_CampaignId] ON [AccessReviewAssignments]([CampaignId]);
    CREATE INDEX [IX_AccessReviewAssignments_ReviewerId] ON [AccessReviewAssignments]([ReviewerId]);
    CREATE INDEX [IX_AccessReviewAssignments_Status] ON [AccessReviewAssignments]([Status]);
    CREATE INDEX [IX_AccessReviewAssignments_DueDate] ON [AccessReviewAssignments]([DueDate]);

    PRINT 'Created AccessReviewAssignments table with indexes';
END
ELSE
BEGIN
    PRINT 'AccessReviewAssignments table already exists';
END
GO

-- ReviewDecisionHistory Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ReviewDecisionHistory')
BEGIN
    CREATE TABLE [ReviewDecisionHistory] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [AssignmentId] uniqueidentifier NOT NULL,
        [CampaignId] uniqueidentifier NOT NULL,
        [Decision] nvarchar(50) NOT NULL,
        [PreviousDecision] nvarchar(50) NULL,
        [Justification] nvarchar(max) NULL,
        [Comments] nvarchar(max) NULL,
        [DecisionMakerId] uniqueidentifier NOT NULL,
        [DecisionMakerName] nvarchar(200) NOT NULL,
        [DecisionMakerEmail] nvarchar(256) NULL,
        [DecisionDate] datetime2 NOT NULL,
        [IpAddress] nvarchar(max) NULL,
        [UserAgent] nvarchar(max) NULL,
        [DecisionContext] nvarchar(max) NULL,
        [RiskScoreAtDecision] int NOT NULL,
        [RiskLevelAtDecision] nvarchar(50) NULL,
        [ComplianceFramework] nvarchar(100) NULL,
        [WasEscalated] bit NOT NULL,
        [WasDelegated] bit NOT NULL,
        CONSTRAINT [FK_ReviewDecisionHistory_Campaigns] FOREIGN KEY ([CampaignId])
            REFERENCES [Campaigns]([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_ReviewDecisionHistory_Assignments] FOREIGN KEY ([AssignmentId])
            REFERENCES [AccessReviewAssignments]([Id]) ON DELETE NO ACTION
    );

    CREATE INDEX [IX_ReviewDecisionHistory_AssignmentId] ON [ReviewDecisionHistory]([AssignmentId]);
    CREATE INDEX [IX_ReviewDecisionHistory_CampaignId] ON [ReviewDecisionHistory]([CampaignId]);
    CREATE INDEX [IX_ReviewDecisionHistory_DecisionDate] ON [ReviewDecisionHistory]([DecisionDate]);
    CREATE INDEX [IX_ReviewDecisionHistory_Decision] ON [ReviewDecisionHistory]([Decision]);

    PRINT 'Created ReviewDecisionHistory table with indexes';
END
ELSE
BEGIN
    PRINT 'ReviewDecisionHistory table already exists';
END
GO

-- RemediationActions Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RemediationActions')
BEGIN
    CREATE TABLE [RemediationActions] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [AssignmentId] uniqueidentifier NOT NULL,
        [CampaignId] uniqueidentifier NOT NULL,
        [DecisionHistoryId] uniqueidentifier NULL,
        [ActionType] nvarchar(50) NOT NULL,
        [ActionDescription] nvarchar(200) NOT NULL,
        [ActionParameters] nvarchar(max) NULL,
        [TargetEntityId] uniqueidentifier NOT NULL,
        [TargetEntityType] nvarchar(50) NOT NULL,
        [Status] nvarchar(50) NOT NULL,
        [ScheduledFor] datetime2 NULL,
        [ExecutedAt] datetime2 NULL,
        [CompletedAt] datetime2 NULL,
        [ExecutionResult] nvarchar(max) NULL,
        [ErrorMessage] nvarchar(max) NULL,
        [RetryCount] int NOT NULL,
        [LastRetryAt] datetime2 NULL,
        [RequiresApproval] bit NOT NULL,
        [ApprovedBy] uniqueidentifier NULL,
        [ApprovedAt] datetime2 NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(200) NOT NULL,
        CONSTRAINT [FK_RemediationActions_Campaigns] FOREIGN KEY ([CampaignId])
            REFERENCES [Campaigns]([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_RemediationActions_Assignments] FOREIGN KEY ([AssignmentId])
            REFERENCES [AccessReviewAssignments]([Id]) ON DELETE NO ACTION
    );

    CREATE INDEX [IX_RemediationActions_AssignmentId] ON [RemediationActions]([AssignmentId]);
    CREATE INDEX [IX_RemediationActions_CampaignId] ON [RemediationActions]([CampaignId]);
    CREATE INDEX [IX_RemediationActions_Status] ON [RemediationActions]([Status]);
    CREATE INDEX [IX_RemediationActions_ScheduledFor] ON [RemediationActions]([ScheduledFor]);

    PRINT 'Created RemediationActions table with indexes';
END
ELSE
BEGIN
    PRINT 'RemediationActions table already exists';
END
GO

-- CampaignTemplates Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CampaignTemplates')
BEGIN
    CREATE TABLE [CampaignTemplates] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [Name] nvarchar(200) NOT NULL,
        [Description] nvarchar(max) NULL,
        [TemplateType] nvarchar(50) NOT NULL,
        [ComplianceFramework] nvarchar(100) NULL,
        [DefaultConfiguration] nvarchar(max) NULL,
        [ScopeConfiguration] nvarchar(max) NULL,
        [NotificationConfiguration] nvarchar(max) NULL,
        [DefaultReviewPeriodDays] int NOT NULL,
        [RecurrencePattern] nvarchar(50) NULL,
        [IsBuiltIn] bit NOT NULL,
        [IsActive] bit NOT NULL,
        [UsageCount] int NOT NULL,
        [LastUsedAt] datetime2 NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(200) NOT NULL,
        [ModifiedAt] datetime2 NULL,
        [ModifiedBy] nvarchar(200) NULL
    );

    CREATE INDEX [IX_CampaignTemplates_TemplateType] ON [CampaignTemplates]([TemplateType]);
    CREATE INDEX [IX_CampaignTemplates_IsActive] ON [CampaignTemplates]([IsActive]);

    PRINT 'Created CampaignTemplates table with indexes';
END
ELSE
BEGIN
    PRINT 'CampaignTemplates table already exists';
END
GO

-- AccessReviewSettings Table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AccessReviewSettings')
BEGIN
    CREATE TABLE [AccessReviewSettings] (
        [Id] uniqueidentifier NOT NULL PRIMARY KEY,
        [DefaultReviewPeriodDays] int NOT NULL,
        [DefaultReminderFrequencyDays] int NOT NULL,
        [RequireJustification] bit NOT NULL,
        [EnableNotifications] bit NOT NULL,
        [AutoRevokeOnExpiry] bit NOT NULL,
        [AllowBulkApproval] bit NOT NULL,
        [DefaultComplianceFramework] nvarchar(100) NULL,
        [EscalationDays] int NOT NULL,
        [AutoCreatePolicyReviews] bit NOT NULL,
        [AutoReviewNewUsers] bit NOT NULL,
        [NewUserReviewDays] int NOT NULL,
        [AutoReviewHighRisk] bit NOT NULL,
        [HighRiskReviewFrequency] nvarchar(50) NOT NULL,
        [AutoReviewGroupMemberships] bit NOT NULL,
        [GroupReviewFrequency] nvarchar(50) NOT NULL,
        [NotificationFromEmail] nvarchar(256) NULL,
        [NotificationFromName] nvarchar(200) NULL,
        [NotificationSubjectTemplate] nvarchar(500) NULL,
        [NotificationBodyTemplate] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NOT NULL,
        [ModifiedAt] datetime2 NULL,
        [ModifiedBy] nvarchar(256) NULL
    );

    PRINT 'Created AccessReviewSettings table';
END
ELSE
BEGIN
    PRINT 'AccessReviewSettings table already exists';
END
GO

PRINT 'Access Review tables creation complete!';
