-- V019: Seed a default standing campaign for compliance violations
-- This ensures the standing campaign exists immediately after setup,
-- rather than being created lazily on first violation triage.

IF NOT EXISTS (SELECT 1 FROM Campaigns WHERE IsRecurring = 1 AND Status = 'Active' AND CampaignType = 'ComplianceReview')
BEGIN
    INSERT INTO Campaigns (
        Id, Name, Description, CampaignType, IsRecurring, Status,
        StartDate, EndDate, ReviewPeriodDays, OnDenialAction,
        AutoRemediateOnDenial, EnableNotifications, ReminderDaysBefore,
        CreatedBy, CreatedAt, TotalAssignments, CompletedAssignments,
        CompletionPercentage, PolicyViolationFilter, IncludeNestedMemberships,
        MaxNestedDepth, CompletionActionsProcessed,
        AutoGenerated, OnIncompleteAction, OnApprovalAction, ExtensionDays
    ) VALUES (
        '00000000-0000-0000-0001-000000000001',
        'Compliance Violations Review',
        'Standing campaign for compliance policy violations. Cases are automatically added when violations are triaged.',
        'ComplianceReview', 1, 'Active',
        GETUTCDATE(), DATEADD(YEAR, 10, GETUTCDATE()), 14, 'RemoveFromGroup',
        1, 1, 3,
        'System', GETUTCDATE(), 0, 0,
        0, 0, 0, 10, 0,
        1, 'None', 'Certify', 7   -- NOT NULL cols (AutoGenerated/OnIncompleteAction/OnApprovalAction/ExtensionDays); values match V022 convention
    );
END
