-- V022: Add SourcePolicyId column and create per-policy standing campaigns
-- Fixes the gap where policies had CreateAccessReview actions but no linked campaign.
-- Also handles the V019 generic campaign (00000000-0000-0000-0001-000000000001).

-- Step 0: Add SourcePolicyId column if it doesn't exist
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('Campaigns') AND name = 'SourcePolicyId')
BEGIN
    ALTER TABLE Campaigns ADD SourcePolicyId uniqueidentifier NULL;
END
GO

-- Recreate the index from V021 in case it failed due to missing column
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('Campaigns') AND name = 'IX_Campaigns_SourcePolicyId')
BEGIN
    CREATE NONCLUSTERED INDEX IX_Campaigns_SourcePolicyId
      ON Campaigns(SourcePolicyId) WHERE SourcePolicyId IS NOT NULL;
END
GO

-- Step 1: Create per-policy standing campaigns for any active policy with CreateAccessReview action
-- that doesn't already have a corresponding campaign
INSERT INTO Campaigns (
    Id, Name, Description, CampaignType, ReviewType, Status,
    StartDate, EndDate, DueDate, ReviewPeriodDays,
    CompletionPercentage, TotalAssignments, CompletedAssignments,
    AutoGenerated, IsRecurring, RecurrencePattern,
    EnableNotifications, ReminderDaysBefore,
    SourcePolicyId,
    OnDenialAction, AutoRemediateOnDenial, OnIncompleteAction, OnApprovalAction, ExtensionDays,
    CompletionActionsProcessed, CreatedBy, CreatedAt,
    PolicyViolationFilter, IncludeNestedMemberships, MaxNestedDepth
)
SELECT
    NEWID(),
    COALESCE(p.DisplayName, p.Name) + ' - Standing Review',
    'Continuous campaign for ' + p.Name + ' violation reviews. Cases are added automatically when violations are detected.',
    'ComplianceReview', 'UserAccess', 'Active',
    GETUTCDATE(), DATEADD(YEAR, 1, GETUTCDATE()), DATEADD(YEAR, 1, GETUTCDATE()), 14,
    0, 0, 0,
    1, 1, 'Continuous',
    1, 3,
    p.Id,
    'RemoveFromGroup', 1, 'None', 'Certify', 7,
    0, 'V022-Migration', GETUTCDATE(),
    0, 0, 10
FROM CompliancePolicies p
INNER JOIN CompliancePolicyAction a ON a.CompliancePolicyId = p.Id
WHERE a.ActionType = 'CreateAccessReview'
  AND a.IsActive = 1
  AND NOT EXISTS (
      SELECT 1 FROM Campaigns c
      WHERE c.SourcePolicyId = p.Id
        AND c.Status NOT IN ('Deleted', 'Archived')
  );

-- Step 2: Reassign any assignments from the V019 generic campaign to the correct per-policy campaigns
UPDATE ara
SET ara.CampaignId = pc.Id
FROM AccessReviewAssignments ara
INNER JOIN Campaigns generic ON ara.CampaignId = generic.Id
    AND generic.Id = '00000000-0000-0000-0001-000000000001'
INNER JOIN CompliancePolicyViolations v ON v.EntityId = ara.ReviewTargetId
INNER JOIN Campaigns pc ON pc.SourcePolicyId = v.CompliancePolicyId
    AND pc.Status NOT IN ('Deleted', 'Archived')
WHERE ara.Status = 'Pending';

-- Step 3: Update campaign statistics for any campaigns that received reassigned assignments
UPDATE c
SET c.TotalAssignments = stats.Total,
    c.CompletedAssignments = stats.Completed,
    c.CompletionPercentage = CASE WHEN stats.Total = 0 THEN 0
        ELSE (CAST(stats.Completed AS DECIMAL) / stats.Total) * 100 END,
    c.ModifiedAt = GETUTCDATE()
FROM Campaigns c
INNER JOIN (
    SELECT CampaignId,
           COUNT(*) AS Total,
           SUM(CASE WHEN Status IN ('Approved', 'Denied', 'Completed') THEN 1 ELSE 0 END) AS Completed
    FROM AccessReviewAssignments
    GROUP BY CampaignId
) stats ON stats.CampaignId = c.Id
WHERE c.AutoGenerated = 1 AND c.IsRecurring = 1;

-- Step 4: Archive the V019 generic campaign if it has no remaining assignments
UPDATE Campaigns
SET Status = 'Archived', ModifiedAt = GETUTCDATE(), ModifiedBy = 'V022-Migration'
WHERE Id = '00000000-0000-0000-0001-000000000001'
  AND NOT EXISTS (
      SELECT 1 FROM AccessReviewAssignments
      WHERE CampaignId = '00000000-0000-0000-0001-000000000001'
  );
