-- V055: Virtual Containers
-- Allows admins to define custom organizational structures for flat
-- identity sources (Entra ID, SCIM, CSV) using attribute-based rules.

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'VirtualContainers')
BEGIN
    CREATE TABLE [VirtualContainers] (
        [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        [ConnectionId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(200) NOT NULL,
        [ParentId] UNIQUEIDENTIFIER NULL,
        [ContainerType] NVARCHAR(50) NOT NULL,
        [AttributeName] NVARCHAR(100) NULL,
        [AttributeValue] NVARCHAR(500) NULL,
        [RuleExpression] NVARCHAR(MAX) NULL,
        [IconClass] NVARCHAR(100) NULL,
        [SortOrder] INT NOT NULL DEFAULT 0,
        [IsAutoGenerated] BIT NOT NULL DEFAULT 0,
        [IsActive] BIT NOT NULL DEFAULT 1,
        [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [ModifiedAt] DATETIME2 NULL,
        CONSTRAINT [PK_VirtualContainers] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_VirtualContainers_Connection] FOREIGN KEY ([ConnectionId])
            REFERENCES [DirectoryConnections] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_VirtualContainers_Parent] FOREIGN KEY ([ParentId])
            REFERENCES [VirtualContainers] ([Id])
    );

    CREATE NONCLUSTERED INDEX [IX_VirtualContainers_Connection]
        ON [VirtualContainers] ([ConnectionId], [IsActive])
        INCLUDE ([ParentId], [ContainerType], [SortOrder]);

    PRINT 'Created VirtualContainers table';
END;
GO

-- Stored proc: Auto-discover virtual containers from synced data
IF OBJECT_ID('dbo.usp_AutoDiscoverVirtualContainers', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AutoDiscoverVirtualContainers;
GO

CREATE PROCEDURE dbo.usp_AutoDiscoverVirtualContainers
    @ConnectionId UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    -- Auto-create containers for each distinct Department
    INSERT INTO VirtualContainers (Id, ConnectionId, Name, ContainerType, AttributeName, AttributeValue, IsAutoGenerated, SortOrder)
    SELECT NEWID(), @ConnectionId, Department, 'Attribute', 'Department', Department, 1, 100
    FROM Objects
    WHERE SourceConnectionId = @ConnectionId AND Department IS NOT NULL AND Department <> ''
      AND Department NOT IN (
          SELECT AttributeValue FROM VirtualContainers
          WHERE ConnectionId = @ConnectionId AND AttributeName = 'Department' AND IsActive = 1
      )
    GROUP BY Department;

    -- Auto-create containers for each distinct Company
    INSERT INTO VirtualContainers (Id, ConnectionId, Name, ContainerType, AttributeName, AttributeValue, IsAutoGenerated, SortOrder)
    SELECT NEWID(), @ConnectionId, Company, 'Attribute', 'Company', Company, 1, 200
    FROM Objects
    WHERE SourceConnectionId = @ConnectionId AND Company IS NOT NULL AND Company <> ''
      AND Company NOT IN (
          SELECT AttributeValue FROM VirtualContainers
          WHERE ConnectionId = @ConnectionId AND AttributeName = 'Company' AND IsActive = 1
      )
    GROUP BY Company;

    -- Auto-create containers for each distinct Office
    INSERT INTO VirtualContainers (Id, ConnectionId, Name, ContainerType, AttributeName, AttributeValue, IsAutoGenerated, SortOrder)
    SELECT NEWID(), @ConnectionId, Office, 'Attribute', 'Office', Office, 1, 300
    FROM Objects
    WHERE SourceConnectionId = @ConnectionId AND Office IS NOT NULL AND Office <> ''
      AND Office NOT IN (
          SELECT AttributeValue FROM VirtualContainers
          WHERE ConnectionId = @ConnectionId AND AttributeName = 'Office' AND IsActive = 1
      )
    GROUP BY Office;

    -- Auto-create containers for each ObjectClass
    INSERT INTO VirtualContainers (Id, ConnectionId, Name, ContainerType, AttributeName, AttributeValue, IsAutoGenerated, SortOrder)
    SELECT NEWID(), @ConnectionId,
        CASE ObjectClass
            WHEN 'user' THEN 'Users'
            WHEN 'group' THEN 'Groups'
            WHEN 'servicePrincipal' THEN 'Service Principals'
            WHEN 'application' THEN 'Applications'
            WHEN 'directoryRole' THEN 'Directory Roles'
            WHEN 'device' THEN 'Devices'
            ELSE ObjectClass
        END,
        'ObjectClass', 'ObjectClass', ObjectClass, 1, 50
    FROM Objects
    WHERE SourceConnectionId = @ConnectionId AND ObjectClass IS NOT NULL
      AND ObjectClass NOT IN (
          SELECT AttributeValue FROM VirtualContainers
          WHERE ConnectionId = @ConnectionId AND AttributeName = 'ObjectClass' AND IsActive = 1
      )
    GROUP BY ObjectClass;

    SELECT @@ROWCOUNT AS ContainersCreated;
END;
GO

PRINT 'V055: Virtual Containers migration complete';
GO
