-- V070: Consolidate the V066-V069 license pool migration mess
-- Previous migrations (V066-V069) created overlapping/duplicate SQL license pools.
-- This migration purges all SkuId LIKE 'SQL-%' rows so pools can be cleanly
-- regenerated by LicensePoolGeneratorService from discovery data.
--
-- Going forward: license pools are auto-generated from discovery, never
-- hardcoded in migrations.

DECLARE @deletedCount INT = 0;

-- Delete any SQL pool rows from the previous messy migrations
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LicensePools')
BEGIN
    -- Remove assignments first (FK safety)
    DELETE FROM LicenseAssignments
    WHERE LicensePoolId IN (SELECT Id FROM LicensePools WHERE SkuId LIKE 'SQL-%');

    DELETE FROM LicensePools WHERE SkuId LIKE 'SQL-%';
    SET @deletedCount = @@ROWCOUNT;

    PRINT 'V070: Purged ' + CAST(@deletedCount AS VARCHAR) + ' legacy SQL license pools from V066-V069.';
    PRINT 'V070: SQL pools will be auto-regenerated by LicensePoolGeneratorService.';
END
GO
