using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLibrary.Models;

/// <summary>
/// Access Review Campaign
/// Maps to Campaigns table
/// </summary>
[Table("Campaigns")]
public class Campaign
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    public string? Description { get; set; }

    // Campaign Type & Configuration
    [Required]
    [MaxLength(50)]
    public string CampaignType { get; set; } = string.Empty;

    /// <summary>
    /// Whether this campaign reviews Objects (AD accounts) or Identities (people).
    /// Values: "Object" (default, backward-compat) or "Identity" (consolidated person-level review).
    /// </summary>
    [MaxLength(50)]
    public string ScopeLevel { get; set; } = "Object";

    [MaxLength(50)]
    public string? ReviewType { get; set; }

    // Scope Definition
    public string? ConnectionScope { get; set; }

    [MaxLength(100)]
    public string? ObjectClassFilter { get; set; }

    public string? DepartmentFilter { get; set; }

    [MaxLength(50)]
    public string? RiskLevelFilter { get; set; }

    public bool PolicyViolationFilter { get; set; }

    public string? CustomScopeFilter { get; set; }

    // Nested Group Membership (for GroupMembershipReview campaigns)
    public bool IncludeNestedMemberships { get; set; }
    public int MaxNestedDepth { get; set; } = 10;

    // Policy Violation Filtering (for PolicyViolationReview campaigns)
    public string? SelectedPolicyIds { get; set; }

    // Timeline
    [Required]
    public DateTime StartDate { get; set; }

    [Required]
    public DateTime EndDate { get; set; }

    public DateTime? DueDate { get; set; }

    [Required]
    public int ReviewPeriodDays { get; set; } = 14;

    // Status & Progress
    [Required]
    [MaxLength(50)]
    public string Status { get; set; } = "Draft";

    public decimal CompletionPercentage { get; set; }

    public int TotalAssignments { get; set; }

    public int CompletedAssignments { get; set; }

    // Automation
    public bool AutoGenerated { get; set; }

    public Guid? SourcePolicyExecutionId { get; set; }

    /// <summary>
    /// Direct link to the compliance policy that owns this standing campaign.
    /// Used for per-policy campaign lookup instead of generic CampaignType queries.
    /// </summary>
    public Guid? SourcePolicyId { get; set; }

    public Guid? ParentCampaignId { get; set; }

    public bool IsRecurring { get; set; }

    public string? RecurrencePattern { get; set; }

    // ── Recurring campaigns (V111) ─────────────────────────────────────────
    /// <summary>
    /// Cadence for recurring campaign generation: 'Weekly', 'Monthly',
    /// 'Quarterly', 'SemiAnnual', or 'Annual'. Null/None for one-time campaigns.
    /// </summary>
    [MaxLength(20)]
    public string? RecurrenceType { get; set; }

    /// <summary>Reserved for custom intervals (e.g. every 2 weeks). Currently unused.</summary>
    public int? RecurrenceInterval { get; set; }

    /// <summary>The first scheduled run date for this recurring series.</summary>
    public DateTime? RecurrenceStartDate { get; set; }

    /// <summary>
    /// When true, CampaignRecurrenceJob will clone this campaign automatically each
    /// time NextScheduledRun is reached. When false, only a notification fires.
    /// </summary>
    public bool AutoLaunch { get; set; }

    /// <summary>
    /// Number of days a cloned campaign should run for. Drives EndDate of the new
    /// child campaign. Defaults to 30.
    /// </summary>
    public int? CampaignDurationDays { get; set; } = 30;

    /// <summary>
    /// Next date the recurrence engine should consider this campaign for cloning.
    /// Updated by CampaignRecurrenceJob each time the campaign is processed.
    /// </summary>
    public DateTime? NextScheduledRun { get; set; }

    /// <summary>When true, the recurrence engine will skip this campaign.</summary>
    public bool IsRecurrencePaused { get; set; }

    /// <summary>
    /// True for campaigns that were created automatically by CampaignRecurrenceJob
    /// from another (parent) recurring campaign. Used to distinguish originals from
    /// generated children in list views.
    /// </summary>
    public bool IsRecurrenceClone { get; set; }

    // Reviewer Assignment Strategy
    [MaxLength(50)]
    public string? AssignmentStrategy { get; set; }

    /// <summary>
    /// When AssignmentStrategy is "SpecificPerson" or "BusinessRole", the target assignee.
    /// </summary>
    public Guid? CaseAssigneeId { get; set; }

    [MaxLength(256)]
    public string? CaseAssigneeName { get; set; }

    // Notifications & Escalation
    public string? NotificationSettings { get; set; }
    public string? EscalationSettings { get; set; }

    public bool EnableNotifications { get; set; }
    public int ReminderDaysBefore { get; set; }

    // Completion Actions - What happens when campaign ends or decisions are made
    /// <summary>
    /// Action to take when a reviewer denies access.
    /// Values: None, RemoveFromGroup, DisableAccount, SendNotification, CreateTicket
    /// </summary>
    [MaxLength(50)]
    public string OnDenialAction { get; set; } = "RemoveFromGroup";

    /// <summary>
    /// Whether to automatically execute remediation when access is denied.
    /// If false, creates a pending remediation action for manual execution.
    /// </summary>
    public bool AutoRemediateOnDenial { get; set; } = true;

    /// <summary>
    /// Action to take when campaign ends with incomplete (pending) assignments.
    /// Values: None, AutoApprove, AutoDeny, Escalate, Extend
    /// </summary>
    [MaxLength(50)]
    public string OnIncompleteAction { get; set; } = "None";

    /// <summary>
    /// If OnIncompleteAction is Escalate, the identity to escalate to.
    /// </summary>
    public Guid? EscalationReviewerId { get; set; }

    /// <summary>
    /// If OnIncompleteAction is Extend, the number of days to extend by.
    /// </summary>
    public int ExtensionDays { get; set; } = 7;

    /// <summary>
    /// Action to take when a reviewer approves access.
    /// Values: Certify, CreateAttestation, UpdateLastCertified
    /// </summary>
    [MaxLength(50)]
    public string OnApprovalAction { get; set; } = "Certify";

    /// <summary>
    /// Whether the campaign completion actions have been processed.
    /// </summary>
    public bool CompletionActionsProcessed { get; set; }

    /// <summary>
    /// When the completion actions were processed.
    /// </summary>
    public DateTime? CompletionActionsProcessedAt { get; set; }

    // Audit
    [Required]
    [MaxLength(256)]
    public string CreatedBy { get; set; } = string.Empty;

    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [MaxLength(256)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    // Compliance Framework
    [MaxLength(100)]
    public string? ComplianceFramework { get; set; }

    // Workflow Integration
    public Guid? WorkflowId { get; set; }

    // Email Template Integration
    public Guid? AssignmentEmailTemplateId { get; set; }
    public Guid? ReminderEmailTemplateId { get; set; }

    // Campaign Owner
    public Guid? OwnerId { get; set; }

    [MaxLength(256)]
    public string? OwnerName { get; set; }

    // CC Emails & Teams Notifications
    [MaxLength(1000)]
    public string? NotificationCcEmails { get; set; }

    public bool EnableTeamsNotifications { get; set; }
}

/// <summary>
/// Access Review Assignment
/// Maps to AccessReviewAssignments table
/// </summary>
[Table("AccessReviewAssignments")]
public class AccessReviewAssignment
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // Campaign Link
    [Required]
    public Guid CampaignId { get; set; }

    // Reviewer
    [Required]
    public Guid ReviewerId { get; set; }

    [MaxLength(256)]
    public string? ReviewerEmail { get; set; }

    [MaxLength(200)]
    public string? ReviewerName { get; set; }

    // Review Target
    [Required]
    public Guid ReviewTargetId { get; set; }

    [Required]
    [MaxLength(50)]
    public string ReviewTargetType { get; set; } = string.Empty;

    [MaxLength(200)]
    public string? ReviewTargetName { get; set; }

    // Context Information
    public string? ContextData { get; set; }
    public int RiskScore { get; set; }

    [MaxLength(50)]
    public string? RiskLevel { get; set; }

    public DateTime? LastAccessDate { get; set; }

    [MaxLength(50)]
    public string? AccessFrequency { get; set; }

    public string? ReasonForAccess { get; set; }

    // Assignment Details
    [Required]
    [MaxLength(50)]
    public string Status { get; set; } = "Pending";

    [Required]
    public DateTime AssignedAt { get; set; } = DateTime.UtcNow;

    public DateTime? DueDate { get; set; }

    public DateTime? CompletedAt { get; set; }

    // Decision
    [MaxLength(50)]
    public string? Decision { get; set; }

    public string? Justification { get; set; }

    public string? Comments { get; set; }

    // Delegation
    public bool IsDelegated { get; set; }
    public Guid? DelegatedTo { get; set; }
    public DateTime? DelegatedAt { get; set; }
    public string? DelegationReason { get; set; }

    // Escalation
    public bool IsEscalated { get; set; }
    public Guid? EscalatedTo { get; set; }
    public DateTime? EscalatedAt { get; set; }
    public string? EscalationReason { get; set; }

    // Notifications
    public int RemindersSent { get; set; }
    public DateTime? LastReminderSent { get; set; }

    // Audit
    public string? IpAddress { get; set; }
    public string? UserAgent { get; set; }

    // Workflow Integration
    public Guid? WorkflowInstanceId { get; set; }

    /// <summary>Campaign name (populated from JOIN, not stored in DB)</summary>
    public string? CampaignName { get; set; }

    // Peer Group (for role-based fallback - first responder pattern)
    /// <summary>
    /// Groups assignments that share completion - when one completes, all are done.
    /// Used when fallback assigns to a BusinessRole with multiple holders.
    /// </summary>
    public Guid? PeerGroupId { get; set; }

    /// <summary>
    /// If completed by a peer in the same PeerGroup, this is their ReviewerId
    /// </summary>
    public Guid? CompletedByPeerId { get; set; }

    /// <summary>
    /// Display name of the peer who completed the assignment
    /// </summary>
    [MaxLength(500)]
    public string? CompletedByPeerName { get; set; }

    // Remediation Tracking (for denial actions like RemoveFromGroup, DisableAccount)
    /// <summary>
    /// Status of remediation action: None, Pending, Completed, Failed
    /// </summary>
    [MaxLength(50)]
    public string? RemediationStatus { get; set; }

    /// <summary>
    /// When remediation was completed
    /// </summary>
    public DateTime? RemediationCompletedAt { get; set; }

    /// <summary>
    /// Details of the remediation action taken
    /// </summary>
    public string? RemediationDetails { get; set; }
}

/// <summary>
/// Review Decision History
/// Maps to ReviewDecisionHistory table - Immutable audit trail
/// </summary>
[Table("ReviewDecisionHistory")]
public class ReviewDecisionHistory
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // Links
    [Required]
    public Guid AssignmentId { get; set; }

    [Required]
    public Guid CampaignId { get; set; }

    // Decision Details
    [Required]
    [MaxLength(50)]
    public string Decision { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? PreviousDecision { get; set; }

    public string? Justification { get; set; }

    public string? Comments { get; set; }

    // Decision Maker
    [Required]
    public Guid DecisionMakerId { get; set; }

    [Required]
    [MaxLength(200)]
    public string DecisionMakerName { get; set; } = string.Empty;

    [MaxLength(256)]
    public string? DecisionMakerEmail { get; set; }

    // Timestamp (Immutable)
    [Required]
    public DateTime DecisionDate { get; set; } = DateTime.UtcNow;

    // Context
    public string? IpAddress { get; set; }
    public string? UserAgent { get; set; }
    public string? DecisionContext { get; set; }

    // Risk Assessment at Decision Time
    public int RiskScoreAtDecision { get; set; }

    [MaxLength(50)]
    public string? RiskLevelAtDecision { get; set; }

    // Compliance
    [MaxLength(100)]
    public string? ComplianceFramework { get; set; }

    public bool WasEscalated { get; set; }
    public bool WasDelegated { get; set; }
}

/// <summary>
/// Remediation Action
/// Maps to RemediationActions table
/// </summary>
[Table("RemediationActions")]
public class RemediationAction
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    // Links
    [Required]
    public Guid AssignmentId { get; set; }

    [Required]
    public Guid CampaignId { get; set; }

    public Guid? DecisionHistoryId { get; set; }

    // Action Details
    [Required]
    [MaxLength(50)]
    public string ActionType { get; set; } = string.Empty;

    [MaxLength(200)]
    public string ActionDescription { get; set; } = string.Empty;

    public string? ActionParameters { get; set; }

    // Target
    [Required]
    public Guid TargetEntityId { get; set; }

    [Required]
    [MaxLength(50)]
    public string TargetEntityType { get; set; } = string.Empty;

    // Status
    [Required]
    [MaxLength(50)]
    public string Status { get; set; } = "Pending";

    public DateTime? ScheduledFor { get; set; }

    public DateTime? ExecutedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    // Execution
    public string? ExecutionResult { get; set; }
    public string? ErrorMessage { get; set; }
    public int RetryCount { get; set; }
    public DateTime? LastRetryAt { get; set; }

    // Approval
    public bool RequiresApproval { get; set; }
    public Guid? ApprovedBy { get; set; }
    public DateTime? ApprovedAt { get; set; }

    // Audit
    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [MaxLength(200)]
    public string CreatedBy { get; set; } = string.Empty;
}

/// <summary>
/// Campaign Template
/// Maps to CampaignTemplates table
/// </summary>
[Table("CampaignTemplates")]
public class CampaignTemplate
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    public string? Description { get; set; }

    // Template Type
    [Required]
    [MaxLength(50)]
    public string TemplateType { get; set; } = string.Empty;

    [MaxLength(100)]
    public string? ComplianceFramework { get; set; }

    // Configuration (JSON)
    public string? DefaultConfiguration { get; set; }
    public string? ScopeConfiguration { get; set; }
    public string? NotificationConfiguration { get; set; }

    // Schedule
    public int DefaultReviewPeriodDays { get; set; } = 14;

    [MaxLength(50)]
    public string? RecurrencePattern { get; set; }

    // Metadata
    public bool IsBuiltIn { get; set; }
    public bool IsActive { get; set; } = true;

    public int UsageCount { get; set; }

    public DateTime? LastUsedAt { get; set; }

    // Audit
    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [MaxLength(200)]
    public string CreatedBy { get; set; } = string.Empty;

    public DateTime? ModifiedAt { get; set; }

    [MaxLength(200)]
    public string? ModifiedBy { get; set; }
}

/// <summary>
/// Access Review Settings
/// Maps to AccessReviewSettings table - Singleton pattern
/// </summary>
[Table("AccessReviewSettings")]
public class AccessReviewSettings
{
    [Key]
    public Guid Id { get; set; } = new Guid("00000000-0000-0000-0000-000000000001");

    // Default Campaign Settings
    [Required]
    public int DefaultReviewPeriodDays { get; set; } = 14;

    [Required]
    public int DefaultReminderFrequencyDays { get; set; } = 3;

    [Required]
    public bool RequireJustification { get; set; } = true;

    [Required]
    public bool EnableNotifications { get; set; } = true;

    [Required]
    public bool AutoRevokeOnExpiry { get; set; } = false;

    [Required]
    public bool AllowBulkApproval { get; set; } = false;

    [MaxLength(100)]
    public string? DefaultComplianceFramework { get; set; }

    [Required]
    public int EscalationDays { get; set; } = 7;

    // Automation Rules
    [Required]
    public bool AutoCreatePolicyReviews { get; set; } = false;

    [Required]
    public bool AutoReviewNewUsers { get; set; } = false;

    [Required]
    public int NewUserReviewDays { get; set; } = 30;

    [Required]
    public bool AutoReviewHighRisk { get; set; } = false;

    [Required]
    [MaxLength(50)]
    public string HighRiskReviewFrequency { get; set; } = "Monthly";

    [Required]
    public bool AutoReviewGroupMemberships { get; set; } = false;

    [Required]
    [MaxLength(50)]
    public string GroupReviewFrequency { get; set; } = "Quarterly";

    // Notification Settings
    [MaxLength(256)]
    public string? NotificationFromEmail { get; set; }

    [MaxLength(200)]
    public string? NotificationFromName { get; set; }

    [MaxLength(500)]
    public string? NotificationSubjectTemplate { get; set; }

    public string? NotificationBodyTemplate { get; set; }

    // Default Campaign Owner & CC
    public Guid? DefaultCampaignOwnerId { get; set; }

    [MaxLength(256)]
    public string? DefaultCampaignOwnerName { get; set; }

    [MaxLength(1000)]
    public string? DefaultNotificationCcEmails { get; set; }

    // Audit
    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Required]
    [MaxLength(256)]
    public string CreatedBy { get; set; } = string.Empty;

    public DateTime? ModifiedAt { get; set; }

    [MaxLength(256)]
    public string? ModifiedBy { get; set; }
}

/// <summary>
/// Campaign Scope Preview Item
/// Used for displaying preview of review targets with assigned reviewers
/// </summary>
public class CampaignScopePreviewItem
{
    // Review Target
    public Guid TargetId { get; set; }
    public string TargetName { get; set; } = string.Empty;
    public string TargetType { get; set; } = string.Empty; // "user", "group", "computer"
    public string? TargetEmail { get; set; }
    public string? TargetDepartment { get; set; }
    public string? TargetUsername { get; set; }

    // Reviewer Assignment
    public Guid? ReviewerId { get; set; }
    public string? ReviewerName { get; set; }
    public string? ReviewerEmail { get; set; }
    public string ReviewerRelationship { get; set; } = "Unassigned"; // "Manager", "Group Owner", "CIO (Fallback)"

    // Assignment Status
    public bool NeedsManualAssignment { get; set; }
    public string? ManualAssignmentReason { get; set; } // "No manager", "No group owner"

    // Context Information
    public string? GroupName { get; set; } // For group membership reviews
    public string? SourceConnection { get; set; }
    public int RiskScore { get; set; }
    public string? RiskLevel { get; set; }

    // Identity-level review fields
    public int LinkedObjectCount { get; set; } // Number of linked AD accounts for this Identity
    public string? LinkedObjectNames { get; set; } // Comma-separated linked account names (for tooltip)
}

/// <summary>
/// Fallback Reviewer Result
/// Returned from stored procedure usp_GetFallbackReviewer
/// </summary>
public class FallbackReviewerResult
{
    public Guid? ReviewerId { get; set; }
    public string? ReviewerName { get; set; }
    public string? ReviewerEmail { get; set; }
    public string ReviewerRelationship { get; set; } = "Unassigned";
    public bool NeedsManualAssignment { get; set; }
    public string? ManualAssignmentReason { get; set; }

    /// <summary>
    /// If set, use all holders of this BusinessRole as reviewers (first responder pattern)
    /// </summary>
    public Guid? BusinessRoleId { get; set; }
}
